create table
  public.records (
    id bigint generated by default as identity,
    given_name text not null,
    family_name text null,
    email text not null,
    date_of_birth date not null,
    score bigint not null default 0,
    data jsonb not null default '"{}"'::jsonb,
    is_okay boolean not null default false,
    created_at timestamp with time zone not null default now(),
    constraint records_pkey primary key (id)
  ) tablespace pg_default;
  